website/front/urls.py
#front/urls.py 
from django.urls import path, re_path
from . import views

app_name = 'front' 

urlpatterns = [
    path('', views.index, name='index'),
    path('faqs/', views.faqs, name='faqs'),
    path('contacts/', views.contacts, name='contacts'),
    path('career/', views.career, name='career'),
    path('privacy-policy/', views.privacy_policy, name='privacy-policy'),
    path('terms-conditions/', views.terms_conditions, name='terms-conditions'),
    path('cookie-policy/', views.cookie_policy, name='cookie-policy'),
    #re_path(r'^(?P<menu_id>[0-9]{2}+)/$', views.menu_by_id),
]

website/restapi_app/urls.py
from django.urls import path, include
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

app_name = 'restapi_app' 

urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),

    path('get-data/', views.get_data),
    path('add-data/', views.add_data),
    path('get-data/<int:data_id>/', views.get_data_by_id),
    path('update-data/<int:data_id>/', views.update_data_by_id),
    path('delete-data/<int:data_id>/', views.delete_data_by_id),
]

website/signals_app/urls.py
from django.urls import path, include
from . import views

app_name = 'signals_app' 

urlpatterns = [
    
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('front.urls', namespace='front')),
    path('api/', include('restapi_app.urls', namespace='restapi_app')),
    path('', include('signals_app.urls', namespace='signals_app')),
]

website/channels_app/models.py
from django.db import models

# Create your models here.

website/front/models.py
from django.db import models

# Create your models here.
class ContactForm(models.Model):
    PROFILE_OPTIONS = {
        "Profile": "Profile",
        "Dashboard": "Dashboard",
        "Services": "Menu (Quotation, Installtion, Service, Other)",
        "Products": "Product List",
        "Invoice": "Invoice History",
        "Other": "Other than Above",
    }

    full_name = models.CharField(max_length=100)
    email = models.CharField(max_length=50)
    profile = models.CharField(max_length=50, choices=PROFILE_OPTIONS)
    file = models.FileField(upload_to='uploads/front/', blank=True, null=True)
    message = models.TextField(max_length=1000, default='')

    def __str__(self):
        return self.full_name + " : " + self.email

website/signals_app/models.py
from django.db import models

# Create your models here.

website/front/forms.py
from django import forms    
from .models import ContactForm

class ContactFormClass(forms.ModelForm):    
    class Meta:
        model = ContactForm
        fields = ("__all__")

website/channels_app/views.py
from django.shortcuts import render

# Create your views here.

website/front/views.py
from django.shortcuts import render
from .forms import ContactFormClass

# Create your views here.
def index(request):
    return render(request, "front/index.html")

def faqs(request):
    if request.method == "POST":
        contact_form = ContactFormClass(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            return render(request, "front/faqs.html", {'contact_form':contact_form, 'contact_form_error': False, 'contact_form_message': 'Successfully submitted.'})
        else:
            return render(request, "front/faqs.html", {'contact_form':contact_form, 'contact_form_error': True, 'contact_form_message': contact_form.errors})
    else:
        contact_form = ContactFormClass()
        return render(request, "front/faqs.html", {'contact_form':contact_form, 'contact_form_error': False, 'contact_form_message': ''})

def contacts(request):
    if request.method == "POST":
        contact_form = ContactFormClass(request.POST, request.FILES)
        if contact_form.is_valid():
            contact_form.save()
            return render(request, "front/contacts.html", {'contact_form':contact_form, 'contact_form_error': False, 'contact_form_message': 'Successfully submitted.'})
        else:
            return render(request, "front/contacts.html", {'contact_form':contact_form, 'contact_form_error': True, 'contact_form_message': contact_form.errors})
    else:
        contact_form = ContactFormClass()
        return render(request, "front/contacts.html", {'contact_form':contact_form, 'contact_form_error': False, 'contact_form_message': ''})

def career(request):
    return render(request, "front/career.html")

def privacy_policy(request):
    return render(request, "front/privacy-policy.html")

def terms_conditions(request):
    return render(request, "front/terms-conditions.html")

def cookie_policy(request):
    return render(request, "front/cookie-policy.html")

website/restapi_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from front.models import ContactForm
from front.serializers import ContactFormSerializer

# for API
from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated

import json

# Create your views here.
@api_view(['GET'])
@permission_classes([IsAuthenticated])
def get_data(request):
    if request.method == 'GET':
        try:
            all_contacts = ContactForm.objects.all()
            serializer_data = ContactFormSerializer(all_contacts, many=True)
            return JsonResponse(serializer_data.data, safe=False)
        except ContactForm.DoesNotExist:
                return JsonResponse({"error": "Contacts not found."}, status=404)

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def get_data_by_id(request, data_id):
    if request.method == 'GET':
        try:
            contact = ContactForm.objects.get(id=data_id)
            serializer_data = ContactFormSerializer(contact)
            return JsonResponse(serializer_data.data, safe=False)
        except ContactForm.DoesNotExist:
            return JsonResponse({"error": "Contact not found."}, status=404)

@api_view(['POST'])
@permission_classes([IsAuthenticated])
def add_data(request):
    if request.method == 'POST':
        serializer_data = ContactFormSerializer(data=request.data)
        if serializer_data.is_valid():
            serializer_data.save()
            return JsonResponse(serializer_data.data, safe=False)
        return JsonResponse({"error": "Somthing wrong."}, status=404)

@api_view(['PUT'])
@permission_classes([IsAuthenticated])
def update_data_by_id(request, data_id):
    if request.method == 'PUT':
        try:
            contact = ContactForm.objects.get(id=data_id)
            serializer_data = ContactFormSerializer(contact, data=request.data, partial=True)
            
            if serializer_data.is_valid():
                serializer_data.save()
                return JsonResponse(serializer_data.data, safe=False, status=200)
            else:
                return JsonResponse(serializer_data.errors, status=400)
        except ContactForm.DoesNotExist:
            return JsonResponse({"error": "Contact not found."}, status=404)
        
@api_view(['DELETE'])
@permission_classes([IsAuthenticated])
def delete_data_by_id(request, data_id):
    try:
        contact = ContactForm.objects.get(id=data_id)
        contact.delete()
        return JsonResponse({"message": "Records deleted."}, status=200)
    except ContactForm.DoesNotExist:
        return JsonResponse({"error": "Contact not found."}, status=404)

website/signals_app/views.py
from django.shortcuts import render

# Create your views here.

website/templates/front/contacts.html
{% load static %}
{% include "layouts/header.html" %}


			<!-- PAGE HERO
			============================================= -->	
			<section id="team-page" class="page-hero-section bg-lightgrey tra-lines division">
				<div class="container">	
					

					<!-- PAGE HERO TEXT -->
					<div class="row">	
						<div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">
							<div class="hero-txt text-center">

								<!-- Title -->
								<h3 class="h3-md">Have Questions Or Need Help?</h3>

								

							</div>
						</div>	
					</div>	<!-- END PAGE HERO TEXT -->


				</div>	   <!-- End container --> 
			</section>	<!-- END PAGE HERO -->	


			<!-- CONTACTS-1
			============================================= -->
			<section id="contacts-1" class="contacts-1 wide-80 contacts-section division">
				<div class="container">


					<div class="row">
						<div class="col-xl-10 offset-xl-1">
				 			<div class="row">


								<!-- CONTACTS INFO -->
						 		<div class="col-md-4">

							 		<!-- LOCATION -->
									<div class="contact-1-box mt-10">
										<h5 class="h5-xs">Our Location</h5>														
										<p class="grey-color">Empire Business Hub, B-1212,<br />  Ahmedabad, Gujarat 380060, India </p>
									</div>

									<!-- PHONES -->
									<div class="contact-1-box">
										<h5 class="h5-xs">Contact Phones</h5>	
										<p class="grey-color">Phone : +12 3 3456 7890</p>
										<p class="grey-color">Fax : +12 9 8765 4321</p>
									</div>

									<!-- WORKING HOURS -->
									<div class="contact-1-box">
										<h5 class="h5-xs">Working Hours</h5>	
										<p class="grey-color">Mon - Fri: 8:30am - 7:30pm</p>
										<p class="grey-color">Sat: 8:30am - 3:30pm</p>
									</div>

								</div>	<!-- END CONTACTS INFO -->


								<!-- CONTACT FORM -->
								<div class="col-md-8">
						            <div class="form-wrapper">
						                <form enctype="multipart/form-data" action="{% url 'front:contacts' %}" method="POST"> 
											{% csrf_token %}
											<table>
												<div class="fieldWrapper">
													{{ contact_form.as_table }}
												  </div>
											<tr>
												<th></th>
												<td><input type="submit"></td>
											</tr>	
											</table>
										</form>
										{% if contact_form_error == True %}
											{{contact_form_message}}
										{% endif %}
						            </div>  
					            </div> 	<!-- END CONTACT FORM --> 


					        </div>
					    </div>
					</div>	<!-- End row -->	


				</div>	   <!-- End container -->		
			</section>	<!-- END CONTACTS-1 -->


			<!-- CALL TO ACTION-1
			============================================= -->
			<section id="cta-1" class="cta-1 bg-01 cta-section division">
				<div class="container white-color">
					<div class="row d-flex align-items-center">


						<!-- CALL TO ACTION TEXT -->
						<div class="col-lg-7">
							<div class="cta-1-txt pr-25">

								<!-- Title -->	
								<h4 class="h4-sm">Let's make something great together</h4>

								

							</div>
						</div>


						<!-- CALL TO ACTION BUTTON -->
						<div class="col-lg-5">
							<div class="cta-1-btn text-right">

								<!-- Button -->
								<a href="{% url 'front:index' %}" class="btn btn-md btn-primary tra-white-hover">Let's Started Now</a>

								
							</div>
						</div>	


					</div>    <!-- End row -->
				</div>	   <!-- End container -->	
			</section>	<!-- END CALL TO ACTION-1 -->


{% include "layouts/footer.html" %}

website/templates/front/faqs.html
{% load static %}
{% include "layouts/header.html" %}

			<!-- PAGE HERO
			============================================= -->	
			<section id="team-page" class="page-hero-section bg-lightgrey tra-lines division">
				<div class="container">	
					

					<!-- PAGE HERO TEXT -->
					<div class="row">	
						<div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">
							<div class="hero-txt text-center">

								<!-- Title -->
								<h3 class="h3-md">Frequently Asked Questions</h3>

								<!-- Text -->
								<!-- <p class="grey-color">Semper lacus cursus porta, feugiat primis ultrice ligula risus auctor rhoncus
								   purus ipsum primis in cubilia vitae laoreet augue
								</p> -->

							</div>
						</div>	
					</div>	<!-- END PAGE HERO TEXT -->


				</div>	   <!-- End container --> 
			</section>	<!-- END PAGE HERO -->	


			<!-- FAQs-1
			============================================= -->
			<section id="faqs-1" class="faqs-1 wide-80 faqs-section division">				
				<div class="container">


					<!-- FAQs-1 QUESTIONS -->	
					<div class="faqs-1-questions pc-15">
						<div class="row">
						

							<!-- QUESTIONS WRAPPER -->
							<div class="col-lg-6">
								<div class="questions-wrapper pc-30">


									<!-- QUESTION #1 -->
									<div class="question">

										<!-- Question -->
										<h5 class="h5-xs"><span>1.</span> What does the main screen display after logging in?</h5>

										<!-- Answer -->
										<p class="p-md grey-color">The main screen shows the schedule for today and the next seven days.
											 If there are no appointments, it will display an empty home page with dates.
										</p>

									</div>	


									<!-- QUESTION #2 -->					
									<div class="question">

										<!-- Question -->
										<h5 class="h5-xs"><span>2.</span>How do I create a new appointment?</h5>

										<!-- Answer -->
										<p class="p-md grey-color">Click on the 'Create' button on the main screen, then select from the four options:
											 Quotation, Installation, Service, or Other, and fill in the required details.
										</p>

									</div>

											
									<!-- QUESTION #3 -->
									<div class="question">

										<!-- Question -->
										<h5 class="h5-xs"><span>3.</span> What happens if I forget to fill in mandatory fields while creating an appointment?</h5>

										<!-- Answer -->
										<p class="p-md grey-color">If you attempt to submit the form with any mandatory fields left empty, 
											an error message will appear stating, “Please fill in all required fields.”

										</p>									

									</div>



								</div>
							</div>	<!-- END QUESTIONS WRAPPER -->


							<!-- QUESTIONS WRAPPER -->
							<div class="col-lg-6">
								<div class="questions-wrapper pc-30">


									
									<!-- QUESTION #4 -->
									<div class="question">
										<!-- Question -->
										<h5 class="h5-xs"><span>4.</span>Can I edit profile, site, or scheduling details after creating an appointment?</h5>
										<!-- Answer -->
										<p class="p-md grey-color">Yes, you can click the edit button on the confirmation page to redirect to the respective profile, 
											site, or scheduling details page for any updates.
										</p>
									</div>	
									<!-- QUESTION #5 -->					
									<div class="question">
										<!-- Question -->
										<h5 class="h5-xs"><span>5.</span>Where can I find all the products?</h5>
										<!-- Answer -->
										<p class="p-md grey-color">You can access all products from the Product List section in the app. Simply click on the Product List page to view all available products and 
										their categories. You can also filter products by category or use the search bar to find specific items.
										</p>
									</div>
									<!-- QUESTION #6 -->
									<div class="question">
										<!-- Question -->
										<h5 class="h5-xs"><span>6.</span> How do I view my quotation or invoice history?</h5>
										<!-- Answer -->
										<p class="p-md grey-color">You can view your last 3 or 6 months' quotations and invoices by clicking on the respective options in the history section.
											 You can also apply custom date filters to see specific records.
										</p>									
									</div>

								</div>
							</div>	<!-- END QUESTIONS WRAPPER -->


						</div>	<!-- End row -->
					</div>	<!-- END FAQs-1 QUESTIONS -->	


				</div>     <!-- End container -->
			</section>	<!-- END FAQs-1 -->


			<!-- CONTACTS-2
			============================================= -->
			<section id="contacts-2" class="contacts-2 bg-lightgrey wide-80 contacts-section division">
				<div class="container">


					<!-- SECTION TITLE -->	
					<div class="row">	
						<div class="col-lg-10 offset-lg-1">
							<div class="section-title mb-60 text-center">		

								<!-- Title 	-->	
								<h3 class="h3-md">Have Questions or Need Help?</h3>	

								
									
							</div>	
						</div>
					</div>


					<!-- CONTACT FORM -->
			        <div class="row">
			            <div class="col-md-10 col-xl-8 offset-md-1 offset-xl-2">
				            <div class="form-wrapper">
				                <form action="{% url 'front:faqs' %}" method="POST"> 
									{% csrf_token %}
									<table>
										<div class="fieldWrapper">
											{{ contact_form.as_table }}
										  </div>
									<tr>
										<th></th>
										<td><input type="submit"></td>
									</tr>	
									</table>
								</form>
								{% if contact_form_error == True %}
									{{contact_form_message}}
								{% endif %} 
				            </div>    
			            </div>  
			        </div>     <!-- END CONTACT FORM -->	


				</div>	   <!-- End container -->		
			</section>	<!-- END CONTACTS-2 -->


{% include "layouts/footer.html" %}

website/templates/layouts/footer.html
{% load static %}
			<!-- FOOTER-6
			============================================= -->
			<section id='footer'>
			
				<footer id="footer-6" class="footer division" style="text-align: center;">
					
					<div class="container">
						<!-- FOOTER CONTENT -->
						
						<div class="grey-color">
							<div class="row">

								<div class="col-md-12">
									<div class="elementor-element elementor-element-5121cba elementor-nav-menu--dropdown-none elementor-nav-menu__align-center elementor-widget elementor-widget-nav-menu" data-id="5121cba" data-element_type="widget" data-settings="{&quot;layout&quot;:&quot;horizontal&quot;,&quot;submenu_icon&quot;:{&quot;value&quot;:&quot;<i class=\&quot;fas fa-caret-down\&quot;><\/i>&quot;,&quot;library&quot;:&quot;fa-solid&quot;}}" data-widget_type="nav-menu.default">
										<div class="elementor-widget-container">
											<link rel="stylesheet" href="https://webstrataegic.com/wp-content/plugins/elementor-pro/assets/css/widget-nav-menu.min.css">
											
											<nav class="elementor-nav-menu--main elementor-nav-menu__container elementor-nav-menu--layout-horizontal e--pointer-none">
												<ul id="menu-1-5121cba" class="elementor-nav-menu sm-horizontal" data-smartmenus-id="17315302857598572">
													<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8046"><a href="{% url 'front:career' %}" class="elementor-item">Career</a></li>
													
													<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8047"><a href="{% url 'front:privacy-policy' %}" class="elementor-item">Privacy Policy</a></li>
													
													<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8049"><a href="{% url 'front:terms-conditions' %}" class="elementor-item">Terms & Conditions</a></li>
													
													<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8049"><a href="{% url 'front:cookie-policy' %}" class="elementor-item">Cookie Policy</a></li>
													
													<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8193"><a href="{% url 'front:faqs' %}" class="elementor-item">FAQ</a></li>
													
													<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8193"><a href="{% url 'front:contacts' %}" class="elementor-item">Contact</a></li>
												</ul>
											</nav>
										</div>
									</div>
								</div>

								<!-- FOOTER COPYRIGHT -->
								<div class="col-md-12">
									<div class="footer-copyright">
										<p>&copy; 2024 - 2030 TaskTrackerPro. All Rights Reserved</p>
									</div>
								</div>

								 <!-- SOCIAL MEDIA ICONS -->
								 <div class="col-md-12">
									<div class="social-icons">
										<a href="https://www.facebook.com/" class="social-icon" target="_blank"><i class="fab fa-facebook-f"></i></a>
										<!-- <a href="#" class="social-icon" target="_blank"><i class="fab fa-twitter"></i></a> -->
										<a href="https://linkedin.in/" class="social-icon" target="_blank"><i class="fab fa-linkedin-in"></i></a>
										<a href="https://instagram.com/" class="social-icon" target="_blank"><i class="fab fa-instagram"></i></a>
									</div>
								</div>
							</div>  <!-- End row -->
						</div>	<!-- END BOTTOM FOOTER -->
					</div>	   <!-- End container -->
					
				</footer>	<!-- END FOOTER-6 -->	
	
				<!-- Add this CSS for spacing between icons -->
				<style>
					.social-icons a {
						margin: 0 10px; /* Adds 10px space between each icon */
						font-size: 20px; /* Adjusts icon size */
						color: #333; /* Sets the color of the icons */
						text-decoration: none;
					}
					.social-icons {
						margin-top: 20px; /* Adds 20px space on top of the icons */
					}
					
					.social-icons a:hover {
						color: #007bff; /* Hover effect color */
					}
				</style>
			</section>


		</div>	<!-- END PAGE CONTENT -->


		<!-- EXTERNAL SCRIPTS
		============================================= -->	
		<script src="{% static 'front/js/jquery-3.4.1.min.js' %}"></script>
		<script src="{% static 'front/js/bootstrap.min.js' %}"></script>	
		<script src="{% static 'front/js/modernizr.custom.js' %}"></script>
		<script src="{% static 'front/js/jquery.easing.js' %}"></script>
		<script src="{% static 'front/js/jquery.appear.js' %}"></script>
		<script src="{% static 'front/js/jquery.scrollto.js' %}"></script>	
		<script src="{% static 'front/js/menu.js' %}"></script>	
		<script src="{% static 'front/js/owl.carousel.min.js' %}"></script>
		<script src="{% static 'front/js/jquery.magnific-popup.min.js' %}"></script>
		<script src="{% static 'front/js/contact-form.js' %}"></script>
		<script src="{% static 'front/js/register-form.js' %}"></script>
		<script src="{% static 'front/js/request-form.js' %}"></script>
		<script src="{% static 'front/js/comment-form.js' %}"></script>	
		<script src="{% static 'front/js/jquery.validate.min.js' %}"></script>
		<script src="{% static 'front/js/jquery.ajaxchimp.min.js' %}"></script>
		<script src="{% static 'front/js/wow.js' %}"></script>		
				
		<!-- Custom Script -->		
		<script src="{% static 'front/js/custom.js' %}"></script>

		<script>
			new WOW().init();
		</script>

			
	</body>
	
</html>	

website/templates/layouts/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

	<head>

		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
		<meta name="author" content="Jthemes"/>	
		<meta name="description" content="Task TrackerPro - Task Management Software"/>
		<meta name="keywords" content="Responsive, HTML5 Template, Jthemes, Landing, Startup, Software, Business, Company, Creative, Freelancers">	
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
				
  		<!-- SITE TITLE -->
		<title>Task TrackerPro - Task Management Software</title>

		<!-- FAVICON AND TOUCH ICONS -->
		<link rel="shortcut icon" href="{% static 'front/images/favicon.png' %}" type="image/x-icon">
		<link rel="icon" href="{% static 'front/images/favicon.png' %}" type="image/x-icon">
		<link rel="apple-touch-icon" sizes="152x152" href="{% static 'front/images/apple-touch-icon-152x152.png' %}">
		<link rel="apple-touch-icon" sizes="120x120" href="{% static 'front/images/apple-touch-icon-120x120.png' %}">
		<link rel="apple-touch-icon" sizes="76x76" href="{% static 'front/images/apple-touch-icon-76x76.png' %}">
		<link rel="apple-touch-icon" href="{% static 'front/images/apple-touch-icon.png' %}">
		<link rel="icon" href="{% static 'front/images/apple-touch-icon.png' %}" type="image/x-icon">

		<!-- GOOGLE FONTS -->
		<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">		
		<link href="https://fonts.googleapis.com/css?family=Noto+Sans+TC:300,400,500,700,900" rel="stylesheet"> 

		<!-- BOOTSTRAP CSS -->
		<link href="{% static 'front/css/bootstrap.min.css' %}" rel="stylesheet">
				
		<!-- FONT ICONS -->
		<link href="https://use.fontawesome.com/releases/v5.11.0/css/all.css" rel="stylesheet" crossorigin="anonymous">		
		<link href="{% static 'front/css/flaticon.css' %}" rel="stylesheet">

		<!-- PLUGINS STYLESHEET -->
		<link href="{% static 'front/css/menu.css' %}" rel="stylesheet">	
		<link id="effect" href="{% static 'front/css/dropdown-effects/fade-down.css' %}" media="all" rel="stylesheet">
		<link href="{% static 'front/css/magnific-popup.css' %}" rel="stylesheet">	
		<link href="{% static 'front/css/owl.carousel.min.css' %}" rel="stylesheet">
		<link href="{% static 'front/css/owl.theme.default.min.css' %}" rel="stylesheet">

		<!-- ON SCROLL ANIMATION -->
		<link href="{% static 'front/css/animate.css' %}" rel="stylesheet">
	
		<link href="{% static 'front/css/skyblue-theme.css' %}" rel="stylesheet">

		<!-- RESPONSIVE CSS -->
		<link href="{% static 'front/css/responsive.css' %}" rel="stylesheet"> 
	
	</head>
		
	<body>


		<!-- PRELOADER SPINNER
		============================================= -->	
		<div id="loader-wrapper">
			<div id="loading">
				<div class="cssload-loader">
					<div class="cssload-ball cssload-ball-1"></div>
					<div class="cssload-ball cssload-ball-2"></div>
					<div class="cssload-ball cssload-ball-3"></div>
					<div class="cssload-ball cssload-ball-4"></div>
				</div>
			</div>
		</div>


		<!-- PAGE CONTENT
		============================================= -->	
		<div id="page" class="page">

			<!-- HEADER ============================================= -->
			<header id="header" class="header tra-menu navbar-dark">

				<div class="header-wrapper">

					<!-- MOBILE HEADER -->
					<div class="wsmobileheader clearfix">	  	
						<span class="smllogo"><img src="{% static 'front/images/logo-01.png' %}" width="155" height="36" alt="mobile-logo"/></span>
						<a id="wsnavtoggle" class="wsanimated-arrow"><span></span></a>	
					</div>

					<!-- NAVIGATION MENU -->
					<div class="wsmainfull menu clearfix pt-2">
					
						<div class="wsmainwp clearfix">

							<!-- LOGO IMAGE -->
							<!-- For Retina Ready displays take a image with double the amount of pixels that your image will be displayed (e.g 310 x 72 pixels) -->
							<div class="desktoplogo"><a href="{% url 'front:index' %}#hero-10" class="logo-black"><img src="{% static 'front/images/logo-01.png' %}" width="155" height="36" alt="header-logo"></a></div>
							<div class="desktoplogo"><a href="{% url 'front:index' %}#hero-10" class="logo-white"><img src="{% static 'front/images/logo-white.png' %}" width="155" height="36" alt="header-logo"></a></div>


							<!-- MAIN MENU -->
							<nav class="wsmenu clearfix">
								<ul class="wsmenu-list">

									<li class="nl-simple" aria-haspopup="true"><a href="{% url 'front:index' %}">Home</a></li>

									<!-- DROPDOWN MENU -->
									<li aria-haspopup="true"><a href="#">About <span class="wsarrow"></span></a>
										<ul class="sub-menu">
											<li aria-haspopup="true"><a href="{% url 'front:index' %}#content-3">Best Solution</a></li>
											<li aria-haspopup="true"><a href="{% url 'front:index' %}#services-5">Core Features</a></li>						           			
											<li aria-haspopup="true"><a href="{% url 'front:index' %}#reviews-3">Testimonials</a></li>	
											<li aria-haspopup="true"><a href="{% url 'front:index' %}#content-2">How It Works</a></li>	
										</ul>
									</li>	<!-- END DROPDOWN MENU -->


									<!-- SIMPLE NAVIGATION LINK -->
									<li class="nl-simple" aria-haspopup="true"><a href="{% url 'front:faqs' %}">FAQs</a></li>

									<!-- SIMPLE NAVIGATION LINK -->
									<li class="nl-simple" aria-haspopup="true"><a href="{% url 'front:contacts' %}">Contact Us</a></li>

									<!-- HEADER BUTTON -->
									<li class="nl-simple" aria-haspopup="true">
										<a href="{% url 'front:index' %}#cta-6" class="btn btn-primary tra-white-hover last-link">Download</a>
									</li>
									
								</ul>
							</nav>	<!-- END MAIN MENU -->

						</div>
					</div>	<!-- END NAVIGATION MENU -->


				</div>     <!-- End header-wrapper -->
			</header>	<!-- END HEADER -->